name: playground
version: 0.1.0.0
github: "githubuser/playground"
license: BSD3
author: "Author name here"
maintainer: "example@example.com"
copyright: "2020 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/playground#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl >=2.0 && < 2.3
  - containers
  - random
  - transformers
  - text
  - text-show
  - lens
library:
  source-dirs: src

executables:
  playground-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -XExistentialQuantification
    dependencies:
      - playground
  simplereader-exe:
    main: simplereader.hs
    source-dirs: simplereader
    dependencies:
      - containers>=0.6.3
  reversepolish-exe:
    main: reversepolish.hs
    source-dirs: reversepolish
  rwst-exe:
    main: rwst.hs
    source-dirs: rwst
  state-exe:
    main: state.hs
    source-dirs: state
  liftio:
    main: liftio.hs
    source-dirs: liftio
    dependencies:
      - transformers
  arrow:
    main: arrow.hs
    source-dirs: arrow
  du:
    main: Main.hs
    source-dirs: du
  exception:
    main: exception.hs
    source-dirs: exceptionT
    dependencies:
      - text-show
  writer:
    main: writer.hs
    source-dirs: writerT
  lenses:
    main: lenses.hs
    source-dirs: lenses
  traversable:
    main: traversable.hs
    source-dirs: traversable
  foldLR:
    main: fold.hs
    source-dirs: foldLWithFoldR
  jsonparser:
    main: jsonparser.hs
    source-dirs: json-parser
  applicative-exe:
    main: app.hs
    source-dirs: applicative
tests:
  playground-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - playground
